// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using PoolWarsV0.Data;

#nullable disable

namespace PoolWarsV0.Data.Migrations
{
    [DbContext(typeof(Context))]
    [Migration("20220803110403_PoolWars")]
    partial class PoolWars
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("PoolWarsV0.Data.Models.CardMetadataDao", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("CardMintId")
                        .HasColumnType("integer");

                    b.Property<int>("Strength")
                        .HasColumnType("integer");

                    b.Property<int>("Type")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("CardMintId")
                        .IsUnique();

                    b.ToTable("CardMetadata");
                });

            modelBuilder.Entity("PoolWarsV0.Data.Models.PoolDao", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("PoolWarId")
                        .HasColumnType("integer");

                    b.Property<string>("PrivateKey")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("Address")
                        .IsUnique();

                    b.HasIndex("PoolWarId");

                    b.HasIndex("PrivateKey")
                        .IsUnique();

                    b.ToTable("Pools");
                });

            modelBuilder.Entity("PoolWarsV0.Data.Models.PoolDepositDao", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("CardMetadataId")
                        .HasColumnType("integer");

                    b.Property<int>("PoolId")
                        .HasColumnType("integer");

                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("CardMetadataId");

                    b.HasIndex("PoolId");

                    b.HasIndex("UserId");

                    b.ToTable("Deposits");
                });

            modelBuilder.Entity("PoolWarsV0.Data.Models.PoolWarDao", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<DateTime>("End")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.ToTable("PoolWars");
                });

            modelBuilder.Entity("PoolWarsV0.Data.Models.SolanaAddress", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Discriminator")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("Address")
                        .IsUnique();

                    b.ToTable("Addresses");

                    b.HasDiscriminator<string>("Discriminator").HasValue("SolanaAddress");
                });

            modelBuilder.Entity("PoolWarsV0.Data.Models.AllowedCreatorAddress", b =>
                {
                    b.HasBaseType("PoolWarsV0.Data.Models.SolanaAddress");

                    b.HasDiscriminator().HasValue("AllowedCreatorAddress");
                });

            modelBuilder.Entity("PoolWarsV0.Data.Models.CardMintAddress", b =>
                {
                    b.HasBaseType("PoolWarsV0.Data.Models.SolanaAddress");

                    b.HasDiscriminator().HasValue("CardMintAddress");
                });

            modelBuilder.Entity("PoolWarsV0.Data.Models.PoolUserDao", b =>
                {
                    b.HasBaseType("PoolWarsV0.Data.Models.SolanaAddress");

                    b.HasDiscriminator().HasValue("PoolUserDao");
                });

            modelBuilder.Entity("PoolWarsV0.Data.Models.CardMetadataDao", b =>
                {
                    b.HasOne("PoolWarsV0.Data.Models.CardMintAddress", "CardMint")
                        .WithMany()
                        .HasForeignKey("CardMintId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CardMint");
                });

            modelBuilder.Entity("PoolWarsV0.Data.Models.PoolDao", b =>
                {
                    b.HasOne("PoolWarsV0.Data.Models.PoolWarDao", "PoolWar")
                        .WithMany("Pools")
                        .HasForeignKey("PoolWarId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("PoolWar");
                });

            modelBuilder.Entity("PoolWarsV0.Data.Models.PoolDepositDao", b =>
                {
                    b.HasOne("PoolWarsV0.Data.Models.CardMetadataDao", "CardMetadata")
                        .WithMany()
                        .HasForeignKey("CardMetadataId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PoolWarsV0.Data.Models.PoolDao", "Pool")
                        .WithMany("Deposits")
                        .HasForeignKey("PoolId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PoolWarsV0.Data.Models.PoolUserDao", "User")
                        .WithMany("Deposits")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CardMetadata");

                    b.Navigation("Pool");

                    b.Navigation("User");
                });

            modelBuilder.Entity("PoolWarsV0.Data.Models.PoolDao", b =>
                {
                    b.Navigation("Deposits");
                });

            modelBuilder.Entity("PoolWarsV0.Data.Models.PoolWarDao", b =>
                {
                    b.Navigation("Pools");
                });

            modelBuilder.Entity("PoolWarsV0.Data.Models.PoolUserDao", b =>
                {
                    b.Navigation("Deposits");
                });
#pragma warning restore 612, 618
        }
    }
}
